before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: kubectl-scan
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - plugin.yaml

snapshot:
  name_template: "{{ .Tag }}-next"
