before:
  hooks:
    - go mod tidy

builds:
  - main: "."
    binary: kubectl-scan
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
    env:
      - CGO_ENABLED=0

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - plugin.yaml
      - LICENSE

snapshot:
  name_template: "{{ .Tag }}-next"
