---
name: Linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Run golangci-lint
        uses: reviewdog/action-golangci-lint@v1.23

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Run yamllint
        uses: reviewdog/action-yamllint@v1.2
