name: Release
on:
  create:
    tags:
      - v*.*.*

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.4
        id: go
        with:
          go-version: ^1.15

      - name: Check out code
        uses: actions/checkout@v2.3.4

      - name: Launch goreleaser
        uses: goreleaser/goreleaser-action@v2.9.0
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
